"""add indexes for pipeline status fields

Revision ID: 9771fd7ad96f
Revises: e39c208594c2
Create Date: 2026-04-03 21:47:08.382458

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9771fd7ad96f"
down_revision: Union[str, Sequence[str], None] = "e39c208594c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_anthropic_articles_digest_status"),
        "anthropic_articles",
        ["digest_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_anthropic_articles_markdown_status"),
        "anthropic_articles",
        ["markdown_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_openai_articles_digest_status"),
        "openai_articles",
        ["digest_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_youtube_videos_digest_status"),
        "youtube_videos",
        ["digest_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_youtube_videos_transcript_status"),
        "youtube_videos",
        ["transcript_status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_youtube_videos_transcript_status"), table_name="youtube_videos"
    )
    op.drop_index(op.f("ix_youtube_videos_digest_status"), table_name="youtube_videos")
    op.drop_index(
        op.f("ix_openai_articles_digest_status"), table_name="openai_articles"
    )
    op.drop_index(
        op.f("ix_anthropic_articles_markdown_status"), table_name="anthropic_articles"
    )
    op.drop_index(
        op.f("ix_anthropic_articles_digest_status"), table_name="anthropic_articles"
    )
    # ### end Alembic commands ###
