"""add status and content metadata fields

Revision ID: e39c208594c2
Revises:
Create Date: 2026-04-02 17:05:47.326762

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e39c208594c2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anthropic_articles",
        sa.Column(
            "markdown_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column("anthropic_articles", sa.Column("markdown_length", sa.Integer(), nullable=True))
    op.add_column(
        "anthropic_articles",
        sa.Column("markdown_failure_reason", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "anthropic_articles",
        sa.Column(
            "content_richness",
            sa.String(length=20),
            server_default="missing",
            nullable=False,
        ),
    )
    op.add_column(
        "anthropic_articles",
        sa.Column(
            "digest_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "anthropic_articles",
        sa.Column("digest_failure_reason", sa.String(length=100), nullable=True),
    )
    op.add_column("openai_articles", sa.Column("content_length", sa.Integer(), nullable=True))
    op.add_column(
        "openai_articles",
        sa.Column(
            "content_richness",
            sa.String(length=20),
            server_default="missing",
            nullable=False,
        ),
    )
    op.add_column(
        "openai_articles",
        sa.Column(
            "content_source_type",
            sa.String(length=20),
            server_default="rss",
            nullable=False,
        ),
    )
    op.add_column(
        "openai_articles",
        sa.Column(
            "digest_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "openai_articles",
        sa.Column("digest_failure_reason", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "youtube_videos",
        sa.Column(
            "transcript_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column("youtube_videos", sa.Column("transcript_length", sa.Integer(), nullable=True))
    op.add_column(
        "youtube_videos",
        sa.Column("transcript_failure_reason", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "youtube_videos",
        sa.Column(
            "content_richness",
            sa.String(length=20),
            server_default="missing",
            nullable=False,
        ),
    )
    op.add_column(
        "youtube_videos",
        sa.Column(
            "digest_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "youtube_videos",
        sa.Column("digest_failure_reason", sa.String(length=100), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("youtube_videos", "digest_failure_reason")
    op.drop_column("youtube_videos", "digest_status")
    op.drop_column("youtube_videos", "content_richness")
    op.drop_column("youtube_videos", "transcript_failure_reason")
    op.drop_column("youtube_videos", "transcript_length")
    op.drop_column("youtube_videos", "transcript_status")
    op.drop_column("openai_articles", "digest_failure_reason")
    op.drop_column("openai_articles", "digest_status")
    op.drop_column("openai_articles", "content_source_type")
    op.drop_column("openai_articles", "content_richness")
    op.drop_column("openai_articles", "content_length")
    op.drop_column("anthropic_articles", "digest_failure_reason")
    op.drop_column("anthropic_articles", "digest_status")
    op.drop_column("anthropic_articles", "content_richness")
    op.drop_column("anthropic_articles", "markdown_failure_reason")
    op.drop_column("anthropic_articles", "markdown_length")
    op.drop_column("anthropic_articles", "markdown_status")
    # ### end Alembic commands ###
